### ISSUE TITLE
Feature Request:: Apple CarPlay/Android Auto Maps to be integrated with HUD

### ISSUE THREAD

**Issue by Sau-pen** [electrichasgoneaudi/q6-e-tron#40]
Request for Audi to provide integration of Google Maps to be integrated with HUD display. Currently HUD only works with full functionality with Audi's own navigation system. Which lacks most alerts like speed camera etc. Either provide those in Audi's navigation or integrated Google Maps with HUD.

**Comment by bwa** [comment]
This is a database for issues, it's very unlikely Audi will use this as input to new features. It's more a tracking of 'this is not working', and when it's is hopefully resolved.
