### ISSUE TITLE
Convenience option for easy seat entry and exit does not work

### ISSUE THREAD

**Issue by bwa** [electrichasgoneaudi/q6-e-tron#8]
If the Audi Q6 has electric adjustable seats and/or electric steering wheel adjustment, there is a MMI option to enable easy entry/exit. The the Audi e-tron exeperience this is working in the way of raise the steering whell and move the seat a couple of centimeters back when car is turen off to make is even easier to leave the car. And when driver enters car later it will restore the seat and steering position when car is started.

This is the MMI option to set the functionality

![image](https://github.com/user-attachments/assets/366b6e39-ab1c-4e2e-ad09-8d1ebe5ee0d8)

**Problem :** It seems to not work at all. Nothing is happening when leaving and nothing is happeing med re-entering the car.

**Comment by KrLinge** [comment]
Same problem, only steering wheel goes up/down. Seat in same position all time. Reported to dealer.

**Comment by bwa** [comment]
My dealer has confirmed this issue and it will be fixed in a software update, but not when that is.

**Comment by bwa** [comment]
Fixed with  [06XM](https://electrichasgoneaudi.net/models/q6-e-tron/knowledgeexchange/updates/patch06xm/)
