### ISSUE TITLE
Impossible to close camera view while reversing

### ISSUE THREAD

**Issue by bwa** [electrichasgoneaudi/q6-e-tron#9]
Audi Q6 har a very well working 360 degree camera view. This is automatically activated when reversing, and the view will change from front camera when D/B mode is used, and rear camera if R is used. You may also press the parking view button to activate, but cannot be used to close it again.

**Problem :** If car is in Reverse, there is now option at all to actually close the view. If gear is in D/B there is actually an X in upper left corner which is closing the camera view, but when i R this is vanished

**Solution :** Add X option in upper left corner also when R is activated.

When drive mode is D/B :

![image](https://github.com/user-attachments/assets/f3f8f3be-7fa7-4a13-b220-a64207220094)

When drivemode is R :

![image](https://github.com/user-attachments/assets/a56d450d-60ab-48f3-a255-79b4af1d4419)

**Comment by roflowhale** [comment]
UNECE R158
https://unece.org/sites/default/files/2021-07/R158e_0.pdf
Uniform provisions concerning the approval of devices for
reversing motion and motor vehicles with regard to the
driver’s awareness of vulnerable road users behind vehicles

Regulation 16.1.1.3.
**Deactivation**
The rear-view image shall remain visible during the backing event until either,

- The driver modifies the view, or the vehicle direction selector is no longer in the reverse position.
- Modifying the view means to switch to any other camera views.
- The view can be manually switched off when the vehicle is not moving rearward.
- The system may be switched off when the vehicle detects a coupling by means of a coupling device.

[R158e_0.pdf](https://github.com/user-attachments/files/17002760/R158e_0.pdf)

**Comment by bwa** [comment]
Annoying, but acceptable. Will close this issue.

**Comment by bwa** [comment]
•	The view can be manually switched off when the vehicle is not moving rearward

@roflowhale This would allow a close option, rigth ? But Audi has choosed to not.
